### ISSUE TITLE
BUG: Compatible Issue

### ISSUE THREAD

**Issue by YingGwan** [eth-ait/aitviewer#16] opened 2022-11-22 18:34 UTC
I have tried to compile aitviewer in windows and ubuntu 20.04, but encountered same problems:

1. Ubuntu: Anaconda; Python = 3.9.7; 
Error detail:
File "/home/yingjun/anaconda3/envs/test/lib/python3.9/site-packages/_moderngl.py", line 344, in <genexpr>
    data = b''.join(struct.pack(self._fmt, *row) for row in value)
TypeError: Value after * must be an iterable, not int

2. Windows 10. Anaconda; Python = 3.9.7
Error Detail:
 File "H:\anaconda3\lib\site-packages\moderngl-5.7.2-py3.9-win-amd64.egg\_moderngl.py", line 344, in <genexpr>
    data = b''.join(struct.pack(self._fmt, *row) for row in value)
TypeError: Value after * must be an iterable, not int

Could you help on this and indicate which version I should use to solve this issue?

**Comment by kaufManu** [comment] 2022-11-22 19:08
Hi @YingGwan 

Thanks for reporting this. I just tested this locally and I was able to reproduce it. It's a problem with moderngl - the latest version seems to have this issue. I was able to resolve this if I downgrade to moderngl 5.6.4, i.e.
```
pip install moderngl==5.6.4
```

Can you let me know if this fixes your problem? If so, we'll get this sorted with the next release.

**Comment by YingGwan** [comment] 2022-11-22 20:53
![fig_resolved](https://user-images.githubusercontent.com/58463326/203419038-25934e0b-a9be-49a4-ad35-9488c38f0e95.png)

This problem has been solved, many thanks!

**Comment by kaufManu** [comment] 2022-11-22 22:05
Good to hear!

I'm opening this again for our reference, to be included in the next release.

The respective bug report in moderngl is: https://github.com/moderngl/moderngl/issues/525
This seems to be a problem as of moderngl version 5.7.1. We can simply fix this by specifying an earlier version in setup.py.

**Comment by YingGwan** [comment] 2022-11-24 22:06
Hi, When I want to load STAR dataset using: 
pip install git+https://github.com/ahmedosman/STAR.git

It appeared this error:
Collecting git+https://github.com/ahmedosman/STAR.git
  Cloning https://github.com/ahmedosman/STAR.git to c:\users\tiany\appdata\local\temp\pip-req-build-lsrye9fk
  Running command git clone -q https://github.com/ahmedosman/STAR.git 'C:\Users\tiany\AppData\Local\Temp\pip-req-build-lsrye9fk'
  Resolved https://github.com/ahmedosman/STAR.git to commit bc6aa8d9be1192ce90d394fdf8898347ec31fe39
    ERROR: Command errored out with exit status 1:
     command: 'H:\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tiany\\AppData\\Local\\Temp\\pip-req-build-lsrye9fk\\setup.py'"'"'; __file__='"'"'C:\\Users\\tiany\\AppData\\Local\\Temp\\pip-req-build-lsrye9fk\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tiany\AppData\Local\Temp\pip-pip-egg-info-0dppz9u7'
         cwd: C:\Users\tiany\AppData\Local\Temp\pip-req-build-lsrye9fk\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tiany\AppData\Local\Temp\pip-req-build-lsrye9fk\setup.py", line 24, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 3989: illegal multibyte sequence
    ----------------------------------------
WARNING: Discarding git+https://github.com/ahmedosman/STAR.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Could you help with it, many thanks!

**Comment by kaufManu** [comment] 2022-11-25 14:48
Hmm, I cannot reproduce this on my machine unfortunately (also Windows).

What if you clone the STAR repo instead and do `python setup.py install` in the cloned directory (or `pip install -e .`)?

**Comment by totomobile43** [comment] 2022-11-28 12:09
Since we cannot reproduce this (and it may be a STAR repo issue), I would suggest trying the following: 

1. Clone the STAR repo locally
2. Modify the setup.py file as follows: On line 23, replace `with open("README.md", "r") as fh:` with `with open("README.md", "r", encoding="UTF-8") as fh:`
3. Run `pip install -e`

Another thing to make sure is that the _path_ that STAR is placed in should only have ascii characters in it.

**Comment by milkshilin** [comment] 2022-12-19 23:59
hello，great job maker，
May i have a question ,when i run Load_STAR, why should i load a STAR Sequece from AMASS data?and i dont know where to get -Female1 run tostand -as a NPZ data.

**Comment by kaufManu** [comment] 2022-12-20 12:13
Hi @milkshilin 

This is just supposed to be an example to get some pose data. If you find it easier, you could just display a T-pose with STAR as follows:
```python
if __name__ == '__main__':
    star_layer = STARLayer(device=C.device)
    star_seq = STARSequence.t_pose(model=star_layer)
    v = Viewer()
    v.scene.add(star_seq)
    v.run()
```
You can download the AMASS data from their [official website](https://amass.is.tue.mpg.de/index.html) (you will have to create a login and accept a license agreement to do so). The npz file we reference in the code can be obtained by downloading the ACCAD SMPL+H G version on the downloads section of the website.

**Comment by kaufManu** [comment] 2022-12-20 13:48
Closing this issue, feel free to re-open if required.

**Closed by kaufManu** 2022-12-20 13:48 UTC
Labels: bug
